### ISSUE TITLE
Play a notification sound before reading the notification message with TTS

### ISSUE THREAD

**Issue by JoLander** [jroal/a2dpvolume#229]
My phone is attached via HFP and A2DP with my cars media device. When I send text messages via TTS to the HFP channel of my car, the music played from the radio stops and the device switches to HFP. Unfortunately, the spoken text has a short delay in the beginning (some milliseconds) where the app name is mentioned.
It would be fine to have the possibility to select a 'jingle' from the notification sounds of the phone which is played before any spoken text.
That would on one hand introduce every new message, and allow the device in my car to read the full text without any gap in the beginning.

**Comment by jroal** [comment]
I have the reader delay in the edit device screen to handle this situation.  It lets you set a delay before reading messages per device.  
![image](https://user-images.githubusercontent.com/893554/48906332-bacf0780-ee29-11e8-8a4d-761d2a8d5891.png)

I know this is not exactly the same since you want a tone but it does fix the issue with not hearing the beginning of the message.
