### ISSUE TITLE
build.gradle

### ISSUE THREAD

**Issue by cprhokie** [jroal/a2dpvolume#254]
First of all thanks Jim for sharing this very useful utiltiy!  I didn't know how else to get you this message.  
When checking out the project and loading into Android Studio 2.3.3 I was unable to get the build to work until I created a build.gradle for the app module.  Until I added build.gradle I was unable to get it to correctly generate R.java for the resources.  Am I missing something?  I have done quite a bit of Android development but am not a gradle expert.  Should the build.gradle for the app module be in the git repo?  Thanks again!

**Comment by jroal** [comment]
I think this is what you are looking for: https://github.com/jroal/a2dpvolume/wiki/Building-APK

I excluded this file because it contains login credentials for the keystore.  I too am a total rookie with Gradle.  Hope that solves your issues.  If not, comment on that wiki thread and we can discuss it there.

**Comment by jroal** [comment]
I implemented this now.  The build.gradle file is now in the repo.
