### ISSUE TITLE
Notifications read more than once

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#278]
Still have issues reading notifications.  Many read twice.

**Comment by cprhokie** [comment]
I will take a look at this.

**Comment by jroal** [comment]
I added a simple check to ensure the same message does not read twice in a row to 2.12.11.7.  It could be better though.

**Comment by jroal** [comment]
I am closing this with 2.12.11.8 for now.  It should fix most of the issues most of the time.

**Comment by cprhokie** [comment]
Reopening because I think I found the real cause.  Hope to have a fix later today.

**Comment by jroal** [comment]
@cprhokie so, what is the root cause then?

**Comment by cprhokie** [comment]
oops I accidentally pushed to this master instead of my own - sorry - I am still learning git - sorry :)  please review the commit...it should fix the double message reading issue.  The basic issue was a receiver being registered by the application sometimes and by the service sometimes and the application one was never being unregistered so there end up being multiple of the same receiver.

**Comment by jroal** [comment]
Interesting.  I had actually implemented about half of that already.  I am no Git expert either.  I was able to work it out though.  I basically put in the same fixes you had.  Some of the variables you marked as unused and commented out are actually used.  One of them was called "talk" and that was actually the flag for knowing if sco was registered, sort of.  Anyway, I cleaned it up now.  Thanks for the help.
